(function(){'use strict';const states={},panels=document.getElementById('panels'),out=document.getElementById('output');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function valid(){document.getElementById('compare').disabled=!document.getElementById('consent').checked||!['before','after'].every(k=>states[k]?.closed);}
for(const key of ['before','after']){
 const box=document.createElement('section');box.className='panel';box.innerHTML='<h2>'+(key==='before'?'Baseline':'Follow-up')+'</h2><input type="file" accept="image/png,image/jpeg,image/webp" aria-label="'+key+' image"><label>Photo date <input type="date" class="date"></label><label>Pixels per millimeter, measured from the ruler <input type="number" class="scale" min="0.01" step="0.01"></label><p class="note">Scale must refer to this displayed, resized image. Draw both lesion and ruler at the same plane. At most 1200 pixels along either edge.</p><canvas width="500" height="300"></canvas><div class="controls"><button class="btn close" disabled>Finish outline</button><button class="btn ghost clear">Clear</button></div>';
 panels.append(box);const c=box.querySelector('canvas'),g=c.getContext('2d'),state={box,c,image:null,points:[],closed:false};states[key]=state;
 function draw(){if(!state.image)return;g.drawImage(state.image,0,0,c.width,c.height);g.beginPath();state.points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));if(state.closed)g.closePath();g.strokeStyle='#145cda';g.lineWidth=3;g.stroke();box.querySelector('.close').disabled=state.points.length<3||state.closed;valid();}
 box.querySelector('[type=file]').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>8000000){out.textContent='Use images below 8 MB.';return;}const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);if(image.width*image.height>6000000){out.textContent='Use images below 6 million pixels.';return;}const scale=Math.min(1,1200/image.width,1200/image.height);c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);state.image=image;state.points=[];state.closed=false;draw();};image.onerror=()=>{URL.revokeObjectURL(url);out.textContent='Could not read image.';};image.src=url;};
 c.onclick=e=>{if(!state.image||state.closed)return;const r=c.getBoundingClientRect();state.points.push({x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height});draw();};
 box.querySelector('.close').onclick=()=>{state.closed=true;draw();};box.querySelector('.clear').onclick=()=>{state.points=[];state.closed=false;draw();};
}
document.getElementById('consent').onchange=valid;
const blob=c=>new Promise(r=>c.toBlob(r,'image/png'));
document.getElementById('compare').onclick=async()=>{
 const f=new FormData();f.append('consent','yes');const button=document.getElementById('compare');button.disabled=true;
 try{
  for(const k of ['before','after']){const s=states[k],date=s.box.querySelector('.date').value,scale=s.box.querySelector('.scale').value;if(!date||!Number.isFinite(Number(scale))||Number(scale)<=0)throw Error('Provide both photo dates and positive ruler scales.');const c=document.createElement('canvas');c.width=s.c.width;c.height=s.c.height;c.getContext('2d').drawImage(s.image,0,0,c.width,c.height);f.append(k==='before'?'previous':'current',await blob(c),k+'.png');const mask=document.createElement('canvas');mask.width=c.width;mask.height=c.height;const g=mask.getContext('2d');g.fillStyle='black';g.fillRect(0,0,c.width,c.height);g.beginPath();s.points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath();g.fillStyle='white';g.fill();f.append('mask_'+k,await blob(mask),'mask.png');f.append('date_'+k,date);f.append('scale_'+k,scale);}
  out.textContent='Comparing measurement and attempting alignment…';const r=await fetch('api/imaging.php?action=compare',{method:'POST',body:f,signal:AbortSignal.timeout(35000)}),d=await r.json();if(!r.ok)throw Error(d.error||'Comparison failed');out.innerHTML='<div class="panel"><h2>Measurement comparison</h2><p>'+d.days_between+' days between photos</p><p>Outlined area: '+d.area_before_mm2+' → '+d.area_after_mm2+' mm²</p><p>Difference: '+d.area_difference_mm2+' mm² ('+d.area_difference_per_day_mm2+' mm²/day)</p><p>Alignment: '+esc(d.alignment.status)+'</p><p>'+esc(d.alignment.notice||d.alignment.reason)+'</p><p class="note">'+esc(d.notice)+'</p></div>';
 }catch(e){out.textContent=e.message;}finally{valid();}
};})();
