(function(){'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');let image=null,points=[],closed=false,stream=null,ready={};
if(new URLSearchParams(location.search).has('embedded'))document.body.classList.add('embedded');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function draw(){if(!image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);if(points.length){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(closed)ctx.closePath();ctx.strokeStyle='#28b5ff';ctx.lineWidth=3;ctx.stroke();if(closed){ctx.fillStyle='#28b5ff22';ctx.fill();}for(const p of points){ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fillStyle='#145cda';ctx.fill();}}}
function refresh(){$('close').disabled=!image||points.length<3||closed;$('analyze').disabled=!closed||!$('consent').checked;$('infer').disabled=!closed||!$('consent').checked||!$('research').checked||!ready[$('architecture').value];}
function load(blob){if(blob.size>8000000){$('status').textContent='Choose an image below 8 MB.';return;}const url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);if(img.naturalWidth*img.naturalHeight>6000000){$('status').textContent='Choose an image below 6 million pixels.';return;}image=img;const scale=Math.min(1,1200/img.width,1200/img.height);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);points=[];closed=false;draw();refresh();$('status').textContent='Click at least three points around the lesion boundary.';};img.onerror=()=>{URL.revokeObjectURL(url);$('status').textContent='Could not read this image.';};img.src=url;}
$('file').addEventListener('change',()=>{if($('file').files[0])load($('file').files[0]);});
canvas.addEventListener('click',e=>{if(!image||closed)return;const r=canvas.getBoundingClientRect();points.push({x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height});draw();refresh();});
$('close').addEventListener('click',()=>{closed=true;draw();refresh();});$('reset').addEventListener('click',()=>{points=[];closed=false;draw();refresh();});
function stop(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('video').hidden=true;$('capture').disabled=true;$('camera-off').disabled=true;$('camera-on').disabled=false;}
$('camera-on').addEventListener('click',async()=>{if(!$('consent').checked){$('status').textContent='Confirm consent before enabling the camera.';return;}if(stream)return;$('camera-on').disabled=true;try{const incoming=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(!$('consent').checked){incoming.getTracks().forEach(t=>t.stop());$('camera-on').disabled=false;return;}stream=incoming;$('video').srcObject=stream;$('video').hidden=false;await $('video').play();$('capture').disabled=false;$('camera-off').disabled=false;}catch(e){stop();$('status').textContent='Camera unavailable. Use HTTPS or localhost and check permission.';}});
$('camera-off').addEventListener('click',stop);$('capture').addEventListener('click',()=>{const v=$('video'),c=document.createElement('canvas');if(!v.videoWidth)return;c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(blob=>{if(blob)load(blob);},'image/png');stop();});
$('consent').addEventListener('change',()=>{if(!$('consent').checked)stop();refresh();});$('research').addEventListener('change',refresh);$('architecture').addEventListener('change',refresh);window.addEventListener('pagehide',stop);
const blob=c=>new Promise(resolve=>c.toBlob(resolve,'image/png'));
async function form(crop=false){const c=document.createElement('canvas');let x=0,y=0,w=canvas.width,h=canvas.height;if(crop){const xs=points.map(p=>p.x),ys=points.map(p=>p.y);x=Math.floor(Math.min(...xs));y=Math.floor(Math.min(...ys));w=Math.max(1,Math.ceil(Math.max(...xs))-x);h=Math.max(1,Math.ceil(Math.max(...ys))-y);}c.width=w;c.height=h;c.getContext('2d').drawImage(image,x/ canvas.width*image.width,y/canvas.height*image.height,w/canvas.width*image.width,h/canvas.height*image.height,0,0,w,h);const f=new FormData();f.append('image',await blob(c),'image.png');f.append('consent','yes');if(!crop){const mask=document.createElement('canvas');mask.width=w;mask.height=h;const g=mask.getContext('2d');g.fillStyle='black';g.fillRect(0,0,w,h);g.beginPath();points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath();g.fillStyle='white';g.fill();f.append('mask',await blob(mask),'mask.png');}return f;}
async function request(action,body){const r=await fetch('api/imaging.php?action='+action,{method:'POST',body,signal:AbortSignal.timeout(35000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Image analysis failed');return d;}
$('analyze').addEventListener('click',async()=>{$('analyze').disabled=true;$('status').textContent='Measuring the outlined region…';try{const d=await request('features',await form());$('features').innerHTML='<div class="metric"><h3>01 · Asymmetry & borders</h3><b>'+d.shape.axis_asymmetry.map(x=>(x*100).toFixed(1)+'%').join(' / ')+'</b><p>Reflection mismatch across two axes. Circularity: '+d.shape.circularity+'. Area: '+d.shape.area_pixels+' pixels. No malignancy threshold.</p></div><div class="metric"><h3>02 · Color variation</h3><b>'+d.color.rgb_std.join(' / ')+'</b><p>Standard deviation of red, green and blue pixels (0–255 scale).</p></div><div class="metric"><h3>03 · Texture</h3><b>'+d.texture.glcm_contrast+'</b><p>GLCM contrast. Homogeneity: '+d.texture.glcm_homogeneity+'; energy: '+d.texture.glcm_energy+'.</p></div><div class="metric"><h3>04 · Vascular architecture</h3><p>'+esc(d.vascular.reason)+'</p></div><div class="metric"><h3>05 · Temporal evolution</h3><p>'+esc(d.temporal.reason)+'</p><a href="followup.html" class="btn ghost">Compare dated images</a></div>';$('status').textContent=d.notice;}catch(e){$('status').textContent=e.message;}finally{refresh();}});
$('infer').addEventListener('click',async()=>{$('infer').disabled=true;try{const f=await form(true);f.append('architecture',$('architecture').value);f.append('research','yes');const d=await request('infer',f);$('model-output').innerHTML='<p class="note">'+esc(d.notice)+'</p>'+Object.entries(d.scores).map(([k,v])=>'<div class="metric"><b>'+esc(k)+'</b> '+Number(v).toFixed(3)+' class score</div>').join('');}catch(e){$('model-output').textContent=e.message;}finally{refresh();}});
fetch('api/imaging.php?action=status').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);Object.entries(d.models||{}).forEach(([k,v])=>ready[k]=v.checkpoint_present);$('model-state').textContent=Object.values(ready).some(Boolean)?'Research checkpoints detected. Scores remain unvalidated.':'No trained checkpoints installed. Capture and descriptive features remain available.';refresh();}).catch(()=>{$('model-state').textContent='Imaging service offline. Start the Python imaging service to enable feature measurements.';});
})();
